# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5cfa41183cc2747b1f1966bd6ef376b66abc0617386ee3b41b3a61cca1d072556c06fd224649104dd956b563c580f03742ef519639cceb93c9b883fc6232a60a

test:
  secret_key_base: 79649403f261e7554956ec17ee4e2f485bd51f4b7439890abe6bb43c31f77280013142d9ebe5bc9b2e285fd68d7cc7e0b30da1c00d6be50575434d378be4ddd3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
